#!/bin/bash

NOW=$(date +"%Y%m%d_%H%M%S")
PY3='stdbuf -o0 nohup python3 -u'

### [train single model with sample rate]
# $PY3 ref/valeriu_mod.py _checkins_ > "./logs/nohup_valeriu_mod_$NOW.log" &
# watch tail -n 30 "./logs/nohup_rec_$NOW.log"

# python3 main.py parse_extra_info 10.0 parse_location_$NOW

# $PY3 main.py skrf_grid_step 0.4 skrf_grid_step_$NOW > "./logs/nohup_skrf_grid_step_$NOW.log" &
# $PY3 main.py xgb_grid_step 1.0 xgb_grid_step_$NOW > "./logs/nohup_skrf_grid_step_$NOW.log" &
# $PY3 main.py skrf_gs_params 0.8 skrf_gs_params_$NOW > "./logs/nohup_skrf_gs_params_$NOW.log" &
# $PY3 main.py skrfp_gs_params 0.8 skrfp_gs_params_$NOW > "./logs/nohup_skrfp_gs_params_$NOW.log" &
# $PY3 main.py sket_gs_params 0.4 sket_gs_params_$NOW > "./logs/nohup_sket_gs_params_$NOW.log" &
# $PY3 main.py xgb_gs_params 0.4 xgb_gs_params_$NOW > "./logs/nohup_xgb_gs_params_$NOW.log" &


# python3 main.py skrf 0.4

# $PY3 main.py all 0.4 all_$NOW > "./logs/all_$NOW.log"  # Fastest for debug use
# python3 main.py skrf 0.8 skrf_$NOW #> "./logs/skrf_$NOW.log" &
# python3 main.py skrf_feats_sel 0.4 skrf_$NOW #> "./logs/skrf_max_cands_$NOW.log" &
# python3 main.py xgb 0.4 xgb_$NOW #> "./logs/xgb_$NOW.log" &

# [KNN]
# python3 main.py knn 0.5 knn_$NOW   # Fastest for debug use
# $PY3 main.py knn_grid_step 1 knn_grid_step_$NOW > "./logs/knn_grid_step_$NOW.log" &
# $PY3 main.py knn_grid_weights 0.5 knn_grid_weights_$NOW > "./logs/knn_grid_weights_$NOW.log" &

# [Specials]
# $PY3 main.py skrf_reverse_valid_split_time 0.8 skrf_reverse_valid_split_time_$NOW > "./logs/skrf_reverse_valid_split_time_$NOW.log" &
# $PY3 main.py skrf_mdl_weights 3.2 skrf_mdl_weights_$NOW > "./logs/skrf_mdl_weights_$NOW.log" &
# $PY3 main.py skrf_gs_loc_th 1.0 skrf_20160607_155730 > "./logs/skrf_gs_loc_th_$NOW.log" &
# $PY3 main.py skrf_gs_place_th 1.0 skrf_20160604_125940 > "./logs/skrf_gs_place_th_$NOW.log" &
# $PY3 main.py skrf_feats_sel 0.8 skrf_feats_sel_$NOW > "./logs/nohup_skrf_feats_sel_$NOW.log" &
# $PY3 main.py skrf_gs_time 1.0 skrf_gs_time_$NOW > "./logs/skrf_gs_time_$NOW.log" &
# $PY3 main.py skrf_place_min_last_checkin 2.0 skrf_skrf_place_min_last_checkin_$NOW > "./logs/skrf_place_min_last_checkin_$NOW.log" &
# $PY3 main.py skrf_train_min_time 1.0 skrf_train_min_time_$NOW > "./logs/skrf_train_min_time_$NOW.log" &
# $PY3 main.py skrf_gs_popu_th 0.4 skrf_20160607_155730 > "./logs/skrf_gs_popu_th_$NOW.log" &
# $PY3 main.py skrf_gs_time_th_wd 0.4 skrf_20160607_155730 > "./logs/skrf_gs_time_th_wd_$NOW.log" &
# $PY3 main.py skrf_gs_time_th_hr 0.4 skrf_gs_time_th_hr_$NOW > "./logs/skrf_gs_time_th_hr_$NOW.log" &
# $PY3 main.py skrf_place_min_checkin 0.4 skrf_place_min_checkin_$NOW > "./logs/skrf_place_min_checkin_$NOW.log" &
# $PY3 main.py skrf_recursive_feature_elimination 0.4 skrf_recursive_feature_elimination_$NOW > "./logs/skrf_recursive_feature_elimination_$NOW.log" &

# [Submits]
# python3 main.py skrf_submit 0.4 skrf_submit_$NOW #> "./logs/nohup_skrf_submit_$NOW.log" &
# $PY3 main.py knn_submit_full 10.0 knn_submit_$NOW > "./logs/knn_submit_$NOW.log" &
# $PY3 main.py knn_try_inter_submit_full 10.0 knn_try_inter_submit_full_$NOW > "./logs/knn_try_inter_submit_full_$NOW.log" &
# $PY3 main.py knn_try_large_grid_submit_full 10.0 knn_try_large_grid_submit_full_$NOW > "./logs/knn_try_large_grid_submit_full_$NOW.log" &
# $PY3 main.py skrf_submit_full 10.0 skrf_submit_full_$NOW > "./logs/nohup_skrf_submit_full_$NOW.log" &
# $PY3 main.py skrfp_submit_full 10.0 skrfp_submit_full_$NOW > "./logs/nohup_skrfp_submit_full_$NOW.log" &
# $PY3 main.py sket_submit_full 10.0 sket_submit_full_$NOW > "./logs/nohup_sket_submit_full_$NOW.log" &
# $PY3 main.py sketp_submit_full 10.0 sketp_submit_full_$NOW > "./logs/nohup_sketp_submit_full_$NOW.log" &
# $PY3 main.py skrf_try_submit 10.0 skrf_try_submit_$NOW > "./logs/skrf_try_submit_$NOW.log" &
# $PY3 main.py xgb_submit 10.0 xgb_submit_$NOW > "./logs/nohup_xgb_submit_$NOW.log" &
$PY3 main.py skrf_submit_rf_family 10.0 skrf_submit_rf_family_$NOW > "./logs/nohup_skrf_submit_rf_family_$NOW.log" &
# $PY3 main.py skrf_submit_et_family 10.0 skrf_submit_et_family_$NOW > "./logs/nohup_skrf_submit_et_family_$NOW.log" &

# $PY3 blending.py blending_$NOW > "./logs/blending_$NOW.log" &

# [Submits Existing Model]
# python3 main.py skrf_eva_exist 0.4 LB_skrf_submit_20160611_233627
# $PY3 main.py skrf_smt_exist 10.0 skrf_submit_20160605_195424 > "./logs/nohup_skrf_submit_20160605_195424.log" &
# $PY3 main.py sketp_smt_exist 10.0 sketp_submit_full_20160622_180604 > "./logs/nohup_sketp_submit_full_20160622_180604.log" &
# python3 main.py xgb_eva_exist 1.0 xgb_gs_params_20160530_041055 > "./logs/nohup_xgb_eva_exist.log" &
# 

# [Kill such processes]
# sudo kill -9 `ps aux | grep "skrf_submit_rf_family" | awk '{print $2}'`