#!/bin/bash

NOW=$(date +"%Y%m%d_%H%M%S")
PY3='stdbuf -o0 nohup python3 -u'

### [train single model with sample rate]
# $PY3 ref/valeriu_mod.py _checkins_ > "./logs/nohup_valeriu_mod_$NOW.log" &
# watch tail -n 30 "./logs/nohup_rec_$NOW.log"

# python3 main.py parse_extra_info 10.0 parse_location_$NOW

# $PY3 main.py skrf_grid_step 1.0 skrf_grid_step_$NOW > "./logs/nohup_skrf_grid_step_$NOW.log" &
# $PY3 main.py xgb_grid_step 1.0 xgb_grid_step_$NOW > "./logs/nohup_skrf_grid_step_$NOW.log" &
# $PY3 main.py skrf_gs_params 1.0 skrf_gs_params_$NOW > "./logs/nohup_skrf_gs_params_$NOW.log" &
# $PY3 main.py xgb_gs_params 0.5 xgb_gs_params_$NOW > "./logs/nohup_xgb_gs_params_$NOW.log" &

# python3 main.py skrf 0.2 skrf_$NOW   # Fastest for debug use

# [Specials]

# $PY3 main.py skrf_gs_loc_th 1.0 skrf_20160607_155730 > "./logs/skrf_gs_loc_th_$NOW.log" &
# $PY3 main.py skrf_gs_place_th 1.0 skrf_20160604_125940 > "./logs/skrf_gs_place_th_$NOW.log" &
# $PY3 main.py skrf_feats_sel 1.0 skrf_feats_sel_$NOW > "./logs/nohup_skrf_feats_sel_$NOW.log" &
# $PY3 main.py skrf_gs_time 1.0 skrf_gs_time_$NOW > "./logs/skrf_gs_time_$NOW.log" &
# $PY3 main.py skrf_place_min_last_checkin 2.0 skrf_skrf_place_min_last_checkin_$NOW > "./logs/skrf_place_min_last_checkin_$NOW.log" &
# $PY3 main.py skrf_train_min_time 1.0 skrf_train_min_time_$NOW > "./logs/skrf_train_min_time_$NOW.log" &
# $PY3 main.py skrf_gs_popu_th 0.4 skrf_20160607_155730 > "./logs/skrf_gs_popu_th_$NOW.log" &
# $PY3 main.py skrf_gs_time_th_wd 0.4 skrf_20160607_155730 > "./logs/skrf_gs_time_th_wd_$NOW.log" &
# $PY3 main.py skrf_gs_time_th_hr 0.4 skrf_20160607_155730 > "./logs/skrf_gs_time_th_hr_$NOW.log" &

# [Submits]
# $PY3 main.py skrf_submit 1.0 skrf_submit_$NOW > "./logs/nohup_skrf_submit_$NOW.log" &
$PY3 main.py skrf_submit 10.0 skrf_submit_$NOW > "./logs/nohup_skrf_submit_$NOW.log" &
# $PY3 main.py xgb_submit 10.0 xgb_submit_$NOW > "./logs/nohup_xgb_submit_$NOW.log" &


# [Submits Existing Model]
# python3 main.py skrf_eva_exist 0.2 skrf_submit_20160605_195424
# $PY3 main.py skrf_smt_exist 10.0 skrf_submit_20160605_195424 > "./logs/nohup_skrf_submit_20160605_195424.log" &
# python3 main.py xgb_eva_exist 1.0 xgb_gs_params_20160530_041055 > "./logs/nohup_xgb_eva_exist.log" &
# 

# [Kill such processes]
# sudo kill -9 `ps aux | grep "skrf" | awk '{print $2}'`